package utils
//请求状态码
const (
	RESPONSE_OK 		= 1   		//请求成功，正常
	RESPONSE_FAIL 		= 0 		//请求失败
	RESPONSE_NOLOGIN 	= -1 		//未登录，无权限
)

//业务逻辑状态码
const (
	RESMSG_OK = "1"
	RESMSG_FAIL = "0"

	//管理员
	RESMSG_SUCCESSLOGIN = "SUCCESS_LOGIN"
	RESMSG_FAILLOGIN = "FAIL_LOGIN"
	RESMSG_SUCCESSSESSION = "SUCCESS_SESSION"
	RESMSG_FAILSESSION = "FAIL_SESSION"
	RESMSG_SUCCESSSIGNOUT = "SUCCESS_SIGNOUT"
	RESMSG_HASNOACCESS = "HAS_NO_ACCESS"
	RESMSG_ERRORADMINCOUNT = "ERROR_ADMIN_COUNT"
	//用户
	RESMSG_ERROR_USERLIST = "ERROR_USERS"
	RESMSG_ERROR_USERINFO = "ERROR_USERINFO"

	//获取订单操作
	RESMSG_ERROR_ORDERLIST = "ERROR_ORDERS"
	RESMSG_ERROR_ORDERINFO = "ERROR_ORDERINFO"
	RESMSG_ERROR_ORDERCOUNT = "ERROR_ORDERCOUNT"

	//商家restaurant
	RESMSG_ERROR_RESTAURANTLIST = "ERROR_RESTAURANTS"
	RESMSG_SUCCESS_ADD_RESTAURANT = "SUCCESS_ADD_RESTAURANT"
	RESMSG_FAIL_ADD_RESTAURANT = "FAIL_ADD_RESTAURANT"
	RESMSG_ERROR_RESTAURANT_INFO = "ERROR_RESTAURANT_INFO"
	RESMSG_SUCCESS_DELETE_SHOP = "SUCCESS_DELETE_SHOP"
	RESMSG_ERROR_SEARCH_ADDRESS = "ERROR_SEARCH_ADDRESS"

	//食品
	RESMSG_ERROR_FOODLIST   = "ERROR_FOODS"
	RESMSG_ERROR_FOODADD    = "ERROR_ADDFOOD"
	RESMSG_SUCCESS_FOODADD  = "SUCCESS_ADDFOOD"
	RESMSG_ERROR_FOODDELE   = "ERROR_DELEFOOD"
	RESMSG_SUCCESS_FOODDELE = "SUCCESS_DELEFOOD"

	//食品种类category
	RESMSG_SUCCESS_ADD_CATEGORY = "SUCCESS_ADD_CATEGORY"
	RESMSG_FAIL_ADD_CATEGORY = 	"FAIL_ADD_CATEGORY"
	RESMSH_ERROR_CATEGORY_LIST = "ERROR_CATEGORIES"

	//文件操作
	RESMSG_ERROR_PICTUREADD = "ERROR_PICTURE_ADD"
	RESMSG_ERROR_PICTURETYPE = "ERROR_PICTURE_TYPE"
	RESMSG_ERROR_PICTURESIZE = "ERROR_PICTURE_SIZE"

	//城市基础表
	RESMSG_ERROR_CITYLIST = "ERROR_CITIES"

	//未登录
	RESMSG_UNLOGIN = "ERROR_UNLOGIN"

	RECODE_UNKNOWN_ERROR = "8000"
)

var recodeText = map[string]string{
	RESMSG_OK 	: "成功",
	RESMSG_FAIL : "失败",

	//管理员
	RESMSG_SUCCESSLOGIN : "管理员登录成功",
	RESMSG_FAILLOGIN : "管理员账号密码错误，登录失败",
	RESMSG_SUCCESSSESSION : "获取管理员信息成功",
	RESMSG_FAILSESSION : "获取管理员信息失败",
	RESMSG_SUCCESSSIGNOUT : "退出成功",
	RESMSG_HASNOACCESS : "您没有该权限",
	RESMSG_ERRORADMINCOUNT : "获取管理员总数失败",
	//用户
	RESMSG_ERROR_USERLIST : "查询用户失败",
	RESMSG_ERROR_USERINFO : "查询用户信息失败",

	//获取订单操作
	RESMSG_ERROR_ORDERLIST : "获取订单失败",
	RESMSG_ERROR_ORDERINFO : "获取用户订单信息失败",
	RESMSG_ERROR_ORDERCOUNT : "获取用户订单数量失败",

	//商家restaurant
	RESMSG_ERROR_RESTAURANTLIST : "查询商家店铺失败",
	RESMSG_SUCCESS_ADD_RESTAURANT : "添加商家店铺成功",
	RESMSG_FAIL_ADD_RESTAURANT : "添加商家店铺失败",
	RESMSG_ERROR_RESTAURANT_INFO : "获取商家店铺信息失败",
	RESMSG_SUCCESS_DELETE_SHOP : "删除商家成功",
	RESMSG_ERROR_SEARCH_ADDRESS : "搜索地址失败",

	//食品
	RESMSG_ERROR_FOODLIST :   "查询食品列表失败",
	RESMSG_ERROR_FOODADD :    "添加食品失败",
	RESMSG_SUCCESS_FOODADD :  "添加食品成功",
	RESMSG_ERROR_FOODDELE :   "删除食品记录失败",
	RESMSG_SUCCESS_FOODDELE : "删除食品记录成功",
	//食品种类category
	RESMSG_SUCCESS_ADD_CATEGORY : "添加食品种类成功",
	RESMSG_FAIL_ADD_CATEGORY : 	"添加食品种类失败",
	RESMSH_ERROR_CATEGORY_LIST : "获取食品种类失败",

	//文件操作
	RESMSG_ERROR_PICTUREADD : "图片上传失败",
	RESMSG_ERROR_PICTURETYPE : "只支持PNG,JPG,JPEG格式的图片",
	RESMSG_ERROR_PICTURESIZE : "图片尺寸太大,请保证在2M一下",

	//城市基础表
	RESMSG_ERROR_CITYLIST : "获取城市信息失败",

	//未登录
	RESMSG_UNLOGIN : "未登录无操作权限，请先登录",

	RECODE_UNKNOWN_ERROR : "服务器未知错误",
}

func Recode2Text(code string) string{
	str,ok :=recodeText[code]
	if ok{
		return str
	}
	return recodeText[RECODE_UNKNOWN_ERROR]
}